### ISSUE TITLE
Cannot submit public comment

### ISSUE THREAD

**Issue by fgregg** [usnationalarchives/federalregister-web#1]
For [this 60-day notice](https://www.federalregister.gov/documents/2017/12/21/2017-27454/agency-information-collection-activities-proposed-ecollection-ecomments-requested-reinstatement-with), clicking on "Submit a public comment on this document" does not provide me a way to submit a public comment on this document? 

Tried in Firefox 58.0 and current Chrome. Ubuntu 16.04. Adblockers turned off.

(I'm not sure if this is the right repository. I also reported this at https://github.com/usnationalarchives/federalregister-api-core/issues/7)

**Comment by peregrinator** [comment]
Hi, it looks like that document had a comment link for a short period of time even though it wasn't intended to. We use a third-party API to determine that and it looks like it may not have initially been set up correctly. If you are looking to comment on that document would reach out to the agency representative mentioned in document directly.

Apologies for any confusion!

**Comment by fgregg** [comment]
Hi @peregrinator, thank you for your response! You may want to keep this issue open since this document still has a link to provide a public comment that does not work. There's also a callout above the document that describes a comment period.

**Comment by peregrinator** [comment]
Hi Forrest - I'll get a fix out for the utility navigation in the sidebar - I believe that's where you're seeing the comment link at this point correct? (missed that when I triaged this earlier!)

The callout at the top of the document is correct, there is an open comment period, however the agency doesn't appear to be using Regulations.gov to collect comments (which is where our comment form would submit comments). Each agency has there own set of rules for how the collect comments that are usually outlined in the document - if you're looking to comment, the closest I see here is: https://www.federalregister.gov/d/2017-27454/p-5

**Comment by peregrinator** [comment]
This has now been resolved to properly take the user to the appropriate place depending on the structure of the document and the availability of a comment url on Regulations.gov
